import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Button, AppBar, Toolbar, IconButton } from "@mui/material";
import Link from "next/link";
import AccountCircleOutlinedIcon from "@mui/icons-material/AccountCircleOutlined";
import SettingsOutlinedIcon from "@mui/icons-material/SettingsOutlined";
import HelpOutlineIcon from "@mui/icons-material/HelpOutline";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anirate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar position="static" color="transparent">
          <Toolbar className="flex justify-between">
            <Link
              href="/"
              className="no-underline text-inherit tracking-[.3em] font-bold font-mono mr-2"
            >
              LOGO
            </Link>
            <div className="grow">
              <Button
                color="inherit"
                component={Link}
                href="/"
                className="normal-case"
              >
                Plans
              </Button>
              <Button
                color="inherit"
                component={Link}
                href="/reports"
                className="normal-case"
              >
                Reports
              </Button>
              <Button
                color="inherit"
                component={Link}
                href="/scenarios"
                className="normal-case"
              >
                Scenarios
              </Button>
            </div>
            <IconButton size="large" aria-haspopup="true" color="inherit">
              <HelpOutlineIcon />
            </IconButton>
            <IconButton size="large" aria-haspopup="true" color="inherit">
              <SettingsOutlinedIcon />
            </IconButton>
            <IconButton size="large" aria-haspopup="true" color="inherit">
              <AccountCircleOutlinedIcon />
            </IconButton>
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  );
}
